name: buildx

on:
    push:
      branches: [ master ]
    workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with: 
            platforms: linux/amd64,linux/arm64
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.docker_username }}
            password: ${{ secrets.docker_password }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: .
            platforms: linux/amd64,linux/arm64
            push: true
            tags: atmollohan/bot:latest
