name: The Will of the People Prevails above all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
          # Docker repository to tag the image with
          repository: atmollohan/bot
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: latest

  test:
    runs-on: ubuntu-latest
    steps:
        - name: Printing
          run: pwd
  
  # deploy:
  #   name: Deploying to AWS
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: executing remote ssh commands using password
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       password: ${{ secrets.PASSWORD }}
  #       script: pwd
